on:
  push:
    branches:
      - main
    paths:
      - "src/pokebattle-api/**"
      - ".github/workflows/api-deploy.yml"

env:
  AZURE_WEBAPP_NAME: pokebattle-api
  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_URL }}

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: ACR authentication
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker Build & Push to ACR
        run: |
          cd src/pokebattle-api
          docker buildx build . -t ${{ env.CONTAINER_REGISTRY }}/{{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
          docker push ${{ env.CONTAINER_REGISTRY }}/{{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}

      # Uncomment the below action snippet if the Web app credentials are not updated as web app settings
      #     - name: Set Web App ACR authentication
      #       uses: Azure/appservice-settings@v1
      #       with:
      #         app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #         app-settings-json: |
      #           [
      #               {
      #                   "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
      #                   "value": "${{ secrets.REGISTRY_PASSWORD }}",
      #                   "slotSetting": false
      #               },
      #               {
      #                   "name": "DOCKER_REGISTRY_SERVER_URL",
      #                   "value": "https://${{ env.CONTAINER_REGISTRY }}",
      #                   "slotSetting": false
      #               },
      #               {
      #                   "name": "DOCKER_REGISTRY_SERVER_USERNAME",
      #                   "value": "${{ secrets.REGISTRY_USERNAME  }}",
      #                   "slotSetting": false
      #               }
      #           ]

      - name: "Deploy to Azure Web App for Container"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.CONTAINER_REGISTRY }}/{{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}
#         startup-command: 'npm start'    # Include start up command to start the app container

